win: User_interface.c Filehandler.c Lib.c Nutritional_database.c
	gcc -o program User_interface.c Filehandler.c Lib.c Nutritional_database.c
	program.exe

mac: User_interface_mac.c Filehandler.c Lib.c Nutritional_database.c
	gcc -o program User_interface_mac.c Filehandler.c Lib.c Nutritional_database.c
	program.exe
